# Generated by Django 5.0.7 on 2024-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('organism_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Organismo')),
                ('organism_name', models.CharField(max_length=50, verbose_name='Nombre del Organismo')),
                ('organism_description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'ordering': ['organism_name'],
            },
        ),
    ]
