# Generated by Django 5.0.7 on 2024-07-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='organism_description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
