# Generated by Django 5.0.9 on 2024-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0002_alter_organism_organism_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='organism_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
