# Generated by Django 5.0.7 on 2024-07-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organismos', '0001_initial'),
        ('personas', '0003_alter_locality_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('service_reason_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Motivo')),
                ('service_reason', models.CharField(max_length=50, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'ordering': ['service_reason'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Atencion')),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('service_modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('service_status', models.BooleanField(verbose_name='¿Se desarrolló el seguimiento correspondiente?')),
                ('service_description', models.TextField(verbose_name='Descripción de la atención')),
                ('organism_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organismos.organism', verbose_name='Organismo interviniente')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.person', verbose_name='Persona atendida')),
                ('service_reason_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atenciones.reason', verbose_name='Motivo')),
            ],
        ),
    ]
