# Generated by Django 5.0.7 on 2024-07-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_date'], 'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
    ]
