# Generated by Django 5.0.7 on 2024-08-22 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0004_alter_service_organism_id'),
        ('organismos', '0002_alter_organism_organism_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-service_date'], 'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterField(
            model_name='service',
            name='organism_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organismos.organism', verbose_name='Organismo interviniente'),
        ),
    ]
