# Generated by Django 5.0.7 on 2024-09-01 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0005_alter_service_options_alter_service_organism_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('headquarter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sede')),
                ('headquarter_name', models.CharField(max_length=100, verbose_name='Nombre Sede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['headquarter_name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario encargado'),
        ),
    ]
