# Generated by Django 5.0.7 on 2024-09-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0007_rename_headquarters_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atenciones.headquarter', verbose_name='Sede de atención'),
        ),
    ]
