# Generated by Django 5.0.7 on 2024-09-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0008_service_service_headquarters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_headquarters',
            new_name='service_headquarter',
        ),
    ]
