# Generated by Django 5.0.9 on 2024-09-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0009_rename_service_headquarters_service_service_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='headquarter_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
