# Generated by Django 5.0.7 on 2024-07-23 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('locality_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Localidad')),
                ('locality_name', models.CharField(max_length=30, verbose_name='Nombre Localidad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['locality_id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Provincia')),
                ('province_name', models.CharField(max_length=25, verbose_name='Nombre Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['province_id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_dni', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='DNI')),
                ('person_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('person_surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('person_birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('person_address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('person_phone', models.IntegerField(verbose_name='Teléfono')),
                ('person_bg_center', models.BooleanField(verbose_name='¿Pertenece al Centro de abuelos?')),
                ('person_observations', models.TextField(verbose_name='Observaciones')),
                ('locality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.locality', verbose_name='ID Localidad')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['person_surname', 'person_dni'],
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.province', verbose_name='ID Provincia'),
        ),
    ]
