# Generated by Django 5.0.7 on 2024-07-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality_name',
            field=models.CharField(max_length=40, verbose_name='Nombre Localidad'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.province', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='locality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.locality', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(max_length=35, verbose_name='Nombre Provincia'),
        ),
    ]
