# Generated by Django 5.0.7 on 2024-07-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_locality_locality_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['locality_name'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['person_surname', 'person_name'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['province_name'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
