# Generated by Django 5.0.7 on 2024-07-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_locality_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
