# Generated by Django 5.0.9 on 2024-10-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_person_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirección'),
        ),
    ]
