# Generated by Django 5.0.9 on 2024-10-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_alter_person_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_dni',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='DNI'),
        ),
    ]
